# Generated by Django 4.0.4 on 2022-07-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planreply',
            name='using_tools',
            field=models.CharField(blank=True, choices=[('using', '使用'), ('nonusing', '未使用')], max_length=50, null=True, verbose_name='ツールを使用しているか'),
        ),
    ]
