# Generated by Django 4.0.4 on 2022-07-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_planreply_using_tools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planreply',
            name='using_tools',
        ),
    ]
