# Generated by Django 4.0.4 on 2022-07-23 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_planreply_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planreply',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.plan'),
        ),
    ]
